### ISSUE TITLE
type : boolean

### ISSUE THREAD

**Issue by penghuima** [xsahxl/apptest#1]
既然在 publish.yaml中定义 internetAccess 为 boolean型
```yaml
    internetAccess:
      type: boolean
      title: 允许公网访问
      description: 配置服务中的函数是否可以访问互联网
      default: true
```
那么在 s.yaml 文件中是不是应该应用  internetAccess 变量为

```yaml
      service:
        name: { { serviceName } }
        description: 欢迎使用ServerlessTool
        internetAccess: {{ internetAccess }}
```
而不是
```yaml
      service:
        name: { { serviceName } }
        description: 欢迎使用ServerlessTool
        internetAccess: "{{ internetAccess }}"
```
